### ISSUE TITLE
Adjust Views - Table format to remove empty columns

### ISSUE THREAD

**Issue by ericholmer** [zebradog/drupal-8-theme-adminlte#13]
When creating an "overview" views based page, there are often different node types that are pulled in that have different fields which are unique per node type. 

Rather than have empty columns for all those Nodes which don't have a given field, there's a code snippet we can add that will automatically hide empty columns in the table. 

Issue described: https://www.drupal.org/node/833176

Issue fix: https://www.drupal.org/node/286580#comment-3219118

**Comment by matt-cook** [comment]
Since we're now breaking views into separate blocks should be a non-issue.
