### ISSUE TITLE
fix view pop-up style

### ISSUE THREAD

**Issue by matt-cook** [zebradog/drupal-8-theme-adminlte#18]
currently  shows under sidebar:

![screen shot 2015-12-18 at 8 33 01 am](https://cloud.githubusercontent.com/assets/626516/11899038/091ee428-a562-11e5-9caf-264a91730de6.png)

**Comment by matt-schuh** [comment]
![screen shot 2016-02-17 at 10 37 41 am](https://cloud.githubusercontent.com/assets/11392191/13116721/8a1e9458-d562-11e5-9aac-dec4292db57b.png)

Also cut off at top (have to find where the top is currently calculated) if modal is tallest it can be (see add menus).  Also, Modal header is now white and unreadable.

**Comment by matt-schuh** [comment]
Fixed header color, but have to find where dimensions are set of modal/content and make sure max width and height don't exceed window height - top bar and window width - side bar.
