### ISSUE TITLE
Padding/Margin Issue 

### ISSUE THREAD

**Issue by ericholmer** [zebradog/drupal-8-theme-adminlte#20]
Appears to be some broken CSS related to the padding of the main container for fields. 

![screen shot 2016-01-06 at 9 22 30 am](https://cloud.githubusercontent.com/assets/7988403/12146029/2177112c-b457-11e5-96c2-03db076b1c2e.png)

**Comment by ericholmer** [comment]
Adding the 'box-body' class seems to give the correct padding as seen in the AdminLTE demo site.

**Comment by matt-schuh** [comment]
Fixed by da8267b
