### ISSUE TITLE
Consider Adding Select Boxes as Featured in AdminLTE using Select2

### ISSUE THREAD

**Issue by ericholmer** [zebradog/drupal-8-theme-adminlte#21]
https://select2.github.io/

Offers some enhanced select box options. 

![screen shot 2016-01-06 at 9 25 28 am](https://cloud.githubusercontent.com/assets/7988403/12146125/94f33d88-b457-11e5-8959-6748b607da54.png)

**Comment by matt-schuh** [comment]
Added in commit 588bbdc

**Comment by matt-schuh** [comment]
I'm reopening this - Select2 boxes need some css adjustments.  In many cases, they aren't wide enough to display all content.  Also, sometimes the scroll wheel won't allow you to scroll to the bottom of the list.

**Comment by matt-schuh** [comment]
Gave full width (like other input boxes) in commit 80266fa
