### ISSUE TITLE
Autocomplete Widget Doesn't work as expected

### ISSUE THREAD

**Issue by ericholmer** [zebradog/drupal-8-theme-adminlte#25]
Not quite sure what's up but Autocomplete for Taxonomy Terms isn't working as expected. 

Perhaps I am confused as to how it's supposed to work but at this point I'm not sure where to go with this.

**Comment by kstangel** [comment]
I believe you can change widgets to AutoComplete at admin/structure/types/manage/project/form-display

Eric - Does this resolve your issue?
