### ISSUE TITLE
Sometimes views edit popups wont appear

### ISSUE THREAD

**Issue by matt-cook** [zebradog/drupal-8-theme-adminlte#28]
Reported by @matt-schuh:

> Seems to be an overall yorkshire bug. Usually they'll work but I've noticed that sometimes after adding a rest export (not sure on other view types) clicking any edit button results in the spinner appearing and disappearing but no popup. The theme has to be changed to edit the affected page.

**Comment by matt-schuh** [comment]
E.g. - Dogtracks: Time view - The page view opens popups fine but the rest export view doesn't.  Interestingly, no errors show in console (apart from a few missing images) and nothing in the network tab of the page inspector shows any issues.  All requests come back with JSON and a code of 200.

**Comment by matt-schuh** [comment]
After deleting the newly added item, then adding it again, the page would no longer show a popup while the existing rest export would.  It seems there can be only one popup.
