### ISSUE TITLE
white text on white background

### ISSUE THREAD

**Issue by matt-cook** [zebradog/drupal-8-theme-adminlte#5]
Unreadable currently. Change to default body color. 
![screen shot 2015-11-30 at 12 52 39 pm](https://cloud.githubusercontent.com/assets/7988403/11481155/426dacd2-9761-11e5-9a19-2cf066e69059.png)

**Comment by matt-cook** [comment]
Also in view edit page:

![screen shot 2015-12-10 at 1 34 22 pm](https://cloud.githubusercontent.com/assets/626516/11726135/cd47000e-9f42-11e5-8a8e-db45d1e13eaf.png)

Should look around see if it's an issue elsewhere and try and fix generally.

**Comment by matt-cook** [comment]
re-opening, still an issue with the drop-down menus in views:

![screen shot 2015-12-11 at 3 53 48 pm](https://cloud.githubusercontent.com/assets/626516/11756437/7831db38-a01f-11e5-8484-109144126526.png)

**Comment by matt-cook** [comment]
@matt-schuh:

![b47ab5e6-d405-11e5-8f46-a4d2cfd14007](https://cloud.githubusercontent.com/assets/626516/13088151/a88f8828-d4b0-11e5-9d7e-7f5bf8877f24.png)

**Comment by matt-schuh** [comment]
Likely fixed by da8267b
Leaving open in case I missed any spots with white text on white background.
